### ISSUE TITLE
get_data in virtual class Sensor has no deleted body

### ISSUE THREAD

**Issue by danielklomp** [HU-R2D2/sensorInterfaces#2]
The virtual method method get_data has no body, but in the header there is no = 0; Won't compile without it

**Comment by iMvBremen** [comment]
Sensor.hpp does have the virtual method "virtual SensorResult get_data() = 0;" right [here](https://github.com/HU-R2D2/sensorInterfaces/blob/development/source/include/Sensor.hpp). What branch/version are you using?
